#[derive(Debug, PartialEq, Eq)]
pub enum OpcodeSyntax {
    // Load/Store
    LDA,
    LDX,
    LDY,
    LAX,
    STA,
    STX,
    STY,
    SAX,
    // Transfer
    TAX,
    TXA,
    TAY,
    TYA,
    TSX,
    TXS,
    // Arithmetic
    ADC,
    SBC,
    INC,
    INX,
    INY,
    DEC,
    DEX,
    DEY,
    DCP,
    // Logical
    AND,
    ORA,
    EOR,
    // Shift/Rotate
    ASL,
    LSR,
    ROL,
    ROR,
    RLA,
    // Compare
    CMP,
    CPX,
    CPY,
    BIT,
    // Branch
    BCC,
    BCS,
    BEQ,
    BNE,
    BMI,
    BPL,
    BVC,
    BVS,
    // Jump/Subroutine
    JMP,
    JSR,
    RTS,
    RTI,
    // Stack
    PHA,
    PHP,
    PLA,
    PLP,
    // Flag
    CLC,
    SEC,
    CLI,
    SEI,
    CLV,
    CLD,
    SED,
    // Control
    NOP,
    BRK,
    KIL,
}

#[derive(Debug, PartialEq, Eq)]
pub enum AddressingMode {
    Absolute,
    AbsoluteX,
    AbsoluteY,
    Accumulator,
    Immediate,
    Implied,
    Indirect,
    IndirectX,
    IndirectY,
    Relative,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
}

pub struct Opcode {
    pub code: u8,
    pub syntax: OpcodeSyntax,
    pub mode: AddressingMode,
    pub bytes: u8,
    pub cycles: u8,
}

impl Opcode {
    pub fn from_u8(code: u8) -> Option<Self> {
        match code {
            // === LOAD/STORE ===
            // LDA - Load Accumulator
            0xA9 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xA5 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xB5 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xAD => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xBD => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0xB9 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0xA1 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0xB1 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDA,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),

            // LDX - Load X Register
            0xA2 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDX,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xA6 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDX,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xB6 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDX,
                mode: AddressingMode::ZeroPageY,
                bytes: 2,
                cycles: 4,
            }),
            0xAE => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDX,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xBE => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDX,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),

            // LDY - Load Y Register
            0xA0 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDY,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xA4 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDY,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xB4 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDY,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xAC => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDY,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xBC => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LDY,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),

            // STA - Store Accumulator
            0x85 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STA,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x95 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STA,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x8D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STA,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x9D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STA,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 5,
            }),
            0x99 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STA,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 5,
            }),
            0x81 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STA,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x91 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STA,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 6,
            }),

            // STX - Store X Register
            0x86 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STX,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x96 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STX,
                mode: AddressingMode::ZeroPageY,
                bytes: 2,
                cycles: 4,
            }),
            0x8E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STX,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),

            // STY - Store Y Register
            0x84 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STY,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x94 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STY,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x8C => Some(Opcode {
                code,
                syntax: OpcodeSyntax::STY,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),

            // === TRANSFER ===
            0xAA => Some(Opcode {
                code,
                syntax: OpcodeSyntax::TAX,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x8A => Some(Opcode {
                code,
                syntax: OpcodeSyntax::TXA,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xA8 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::TAY,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x98 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::TYA,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xBA => Some(Opcode {
                code,
                syntax: OpcodeSyntax::TSX,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x9A => Some(Opcode {
                code,
                syntax: OpcodeSyntax::TXS,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),

            // === ARITHMETIC ===
            // ADC - Add with Carry
            0x69 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x65 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x75 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x6D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x7D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x79 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x61 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x71 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ADC,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),

            // SBC - Subtract with Carry
            0xE9 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xE5 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xF5 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xED => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xFD => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0xF9 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0xE1 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0xF1 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),

            // INC/DEC Memory
            0xE6 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::INC,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0xF6 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::INC,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0xEE => Some(Opcode {
                code,
                syntax: OpcodeSyntax::INC,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0xFE => Some(Opcode {
                code,
                syntax: OpcodeSyntax::INC,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),

            0xC6 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DEC,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0xD6 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DEC,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0xCE => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DEC,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0xDE => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DEC,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),

            // INC/DEC Registers
            0xE8 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::INX,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xC8 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::INY,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xCA => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DEX,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x88 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DEY,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),

            // === LOGICAL ===
            // AND - Bitwise AND
            0x29 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x25 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x35 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x2D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x3D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x39 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x21 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x31 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::AND,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),

            // ORA - Bitwise OR
            0x09 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x05 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x15 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x0D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x1D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x19 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x01 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x11 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ORA,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),

            // EOR - Bitwise Exclusive OR
            0x49 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0x45 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x55 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x4D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x5D => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0x59 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x41 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0x51 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::EOR,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),

            // === SHIFT/ROTATE ===
            // ASL - Arithmetic Shift Left
            0x0A => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ASL,
                mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x06 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ASL,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x16 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ASL,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x0E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ASL,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x1E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ASL,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),

            // LSR - Logical Shift Right
            0x4A => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LSR,
                mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x46 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LSR,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x56 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LSR,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x4E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LSR,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x5E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LSR,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),

            // ROL - Rotate Left
            0x2A => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROL,
                mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x26 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROL,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x36 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROL,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x2E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROL,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x3E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROL,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),

            // ROR - Rotate Right
            0x6A => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROR,
                mode: AddressingMode::Accumulator,
                bytes: 1,
                cycles: 2,
            }),
            0x66 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROR,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x76 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROR,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0x6E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROR,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x7E => Some(Opcode {
                code,
                syntax: OpcodeSyntax::ROR,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),

            // === COMPARE ===
            // CMP - Compare Accumulator
            0xC9 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xC5 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xD5 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0xCD => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xDD => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),
            0xD9 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0xC1 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0xD1 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CMP,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 5,
            }),

            // CPX - Compare X Register
            0xE0 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CPX,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xE4 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CPX,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xEC => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CPX,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),

            // CPY - Compare Y Register
            0xC0 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CPY,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),
            0xC4 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CPY,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xCC => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CPY,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),

            // BIT - Test Bits
            0x24 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BIT,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x2C => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BIT,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),

            // === BRANCH ===
            0x10 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BPL,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x30 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BMI,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x50 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BVC,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x70 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BVS,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0x90 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BCC,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0xB0 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BCS,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0xD0 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BNE,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),
            0xF0 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BEQ,
                mode: AddressingMode::Relative,
                bytes: 2,
                cycles: 2,
            }),

            // === JUMP/SUBROUTINE ===
            0x4C => Some(Opcode {
                code,
                syntax: OpcodeSyntax::JMP,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 3,
            }),
            0x6C => Some(Opcode {
                code,
                syntax: OpcodeSyntax::JMP,
                mode: AddressingMode::Indirect,
                bytes: 3,
                cycles: 5,
            }),
            0x20 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::JSR,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x60 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RTS,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 6,
            }),
            0x40 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RTI,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 6,
            }),

            // === STACK ===
            0x48 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::PHA,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 3,
            }),
            0x08 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::PHP,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 3,
            }),
            0x68 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::PLA,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 4,
            }),
            0x28 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::PLP,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 4,
            }),

            // === FLAGS ===
            0x18 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CLC,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x38 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SEC,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x58 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CLI,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0x78 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SEI,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xB8 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CLV,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xD8 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::CLD,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),
            0xF8 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SED,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),

            // === CONTROL ===
            0xEA => Some(Opcode {
                code,
                syntax: OpcodeSyntax::NOP,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),

            0x00 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::BRK,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 7,
            }),

            // ==== UNOFFICIAL OPCODES ====

            // ==== NO OP ====
            0x1A | 0x3A | 0x5A | 0x7A | 0xDA | 0xFA => Some(Opcode {
                code,
                syntax: OpcodeSyntax::NOP,
                mode: AddressingMode::Implied,
                bytes: 1,
                cycles: 2,
            }),

            0x80 | 0x82 | 0x89 | 0xC2 | 0xE2 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::NOP,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),

            0x04 | 0x44 | 0x64 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::NOP,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x14 | 0x34 | 0x54 | 0x74 | 0xD4 | 0xF4 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::NOP,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 4,
            }),
            0x0C => Some(Opcode {
                code,
                syntax: OpcodeSyntax::NOP,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),

            0x1C | 0x3C | 0x5C | 0x7C | 0xDC | 0xFC => Some(Opcode {
                code,
                syntax: OpcodeSyntax::NOP,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 4,
            }),

            // ==== LOAD ====
            0xA3 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LAX,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 6,
            }),
            0xB3 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LAX,
                mode: AddressingMode::ZeroPageY,
                bytes: 2,
                cycles: 5,
            }),
            0xA7 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LAX,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0xB7 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LAX,
                mode: AddressingMode::ZeroPageY,
                bytes: 2,
                cycles: 4,
            }),
            0xAF => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LAX,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0xBF => Some(Opcode {
                code,
                syntax: OpcodeSyntax::LAX,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 4,
            }),
            0x87 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SAX,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 3,
            }),
            0x97 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SAX,
                mode: AddressingMode::ZeroPageY,
                bytes: 2,
                cycles: 4,
            }),
            0x8F => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SAX,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 4,
            }),
            0x83 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SAX,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 6,
            }),

            0xEB => Some(Opcode {
                code,
                syntax: OpcodeSyntax::SBC,
                mode: AddressingMode::Immediate,
                bytes: 2,
                cycles: 2,
            }),

            0xC7 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DCP,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0xD7 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DCP,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),
            0xCF => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DCP,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0xDF => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DCP,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            0xDB => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DCP,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 7,
            }),
            0xC3 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DCP,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 8,
            }),
            0xD3 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::DCP,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 8,
            }),

            0x27 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RLA,
                mode: AddressingMode::ZeroPage,
                bytes: 2,
                cycles: 5,
            }),
            0x37 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RLA,
                mode: AddressingMode::ZeroPageX,
                bytes: 2,
                cycles: 6,
            }),

            0x2F => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RLA,
                mode: AddressingMode::Absolute,
                bytes: 3,
                cycles: 6,
            }),
            0x3F => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RLA,
                mode: AddressingMode::AbsoluteX,
                bytes: 3,
                cycles: 7,
            }),
            0x3B => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RLA,
                mode: AddressingMode::AbsoluteY,
                bytes: 3,
                cycles: 7,
            }),

            0x23 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RLA,
                mode: AddressingMode::IndirectX,
                bytes: 2,
                cycles: 8,
            }),

            0x33 => Some(Opcode {
                code,
                syntax: OpcodeSyntax::RLA,
                mode: AddressingMode::IndirectY,
                bytes: 2,
                cycles: 8,
            }),

            // KIL / JAM (Halt CPU)
            0x02 | 0x12 | 0x22 | 0x32 | 0x42 | 0x52 | 0x62 | 0x72 | 0x92 | 0xB2 | 0xD2 | 0xF2 => {
                Some(Opcode {
                    code,
                    syntax: OpcodeSyntax::KIL,
                    mode: AddressingMode::Implied, // It doesn't really matter, it just dies
                    bytes: 1,
                    cycles: 0,
                })
            }
            _ => None,
        }
    }
}
